### ISSUE TITLE
コンドーム - 月、曜日別のレシート数の集計

### ISSUE THREAD

**Issue by tatsuro1992** [cloudspiral-c9/PBL1#8]
コンドーム - 月、曜日別のレシート数の集計

**Comment by tatsuro1992** [comment]
2014/10/07 集計完了　GitHubにて共有の方法が分からない...

**Comment by cloudspiral-c9** [comment]
作ったブランチをリモートにpushしてくれれば、大丈夫やで(^^)

あとは、作ったブランチからmasterにpullrequestかけてくれれば他の人がレビューできるようになります！
